import MyAsksSection from "./MyAsksSection"
import MyHelpOffersSection from "./MyHelpOffersSection"

export default function DashboardPage({
  myAsks,
  offersForMyAsks,
  stories,
  expandedAskId,
  setExpandedAskId,
  editingAskId,
  setEditingAskId,
  editAskForm,
  setEditAskForm,
  handleSaveAskEdit,
  handleDeleteAsk,
  activeTheme,
  handleProfileClick,
  setGratitudeAskId,
  setIsGratitudeOpen,
  handleAcceptOffer,
  handleDeclineOffer,
  handleFulfillOffer,
  getMessagesForOffer,
  getUnreadMessagesForOffer,
  expandedMessagesOfferId,
  setExpandedMessagesOfferId,
  currentUserId,
  messageInputs,
  setMessageInputs,
  handleSendMessage,
  handleMarkMessagesAsRead,
  editingStoryId,
  setEditingStoryId,
  editStoryForm,
  setEditStoryForm,
  handleDeleteStory,
  handleSaveStoryEdit,

  myHelpOffers,
  asks,
  expandedHelpOfferId,
  setExpandedHelpOfferId,
  editingOfferId,
  setEditingOfferId,
  editOfferForm,
  setEditOfferForm,
  handleSaveOfferEdit,
  handleWithdrawOffer,
}) {
  return (
    <>
      <MyAsksSection
        myAsks={myAsks}
        offersForMyAsks={offersForMyAsks}
        stories={stories}
        expandedAskId={expandedAskId}
        setExpandedAskId={setExpandedAskId}
        editingAskId={editingAskId}
        setEditingAskId={setEditingAskId}
        editAskForm={editAskForm}
        setEditAskForm={setEditAskForm}
        handleSaveAskEdit={handleSaveAskEdit}
        handleDeleteAsk={handleDeleteAsk}
        activeTheme={activeTheme}
        handleProfileClick={handleProfileClick}
        setGratitudeAskId={setGratitudeAskId}
        setIsGratitudeOpen={setIsGratitudeOpen}
        handleAcceptOffer={handleAcceptOffer}
        handleDeclineOffer={handleDeclineOffer}
        handleFulfillOffer={handleFulfillOffer}
        getMessagesForOffer={getMessagesForOffer}
        getUnreadMessagesForOffer={getUnreadMessagesForOffer}
        expandedMessagesOfferId={expandedMessagesOfferId}
        setExpandedMessagesOfferId={setExpandedMessagesOfferId}
        currentUserId={currentUserId}
        messageInputs={messageInputs}
        setMessageInputs={setMessageInputs}
        handleSendMessage={handleSendMessage}
        handleMarkMessagesAsRead={handleMarkMessagesAsRead}
        editingStoryId={editingStoryId}
        setEditingStoryId={setEditingStoryId}
        editStoryForm={editStoryForm}
        setEditStoryForm={setEditStoryForm}
        handleDeleteStory={handleDeleteStory}
        handleSaveStoryEdit={handleSaveStoryEdit}
      />

      <MyHelpOffersSection
        myHelpOffers={myHelpOffers}
        asks={asks}
        expandedHelpOfferId={expandedHelpOfferId}
        setExpandedHelpOfferId={setExpandedHelpOfferId}
        handleProfileClick={handleProfileClick}
        editingOfferId={editingOfferId}
        setEditingOfferId={setEditingOfferId}
        editOfferForm={editOfferForm}
        setEditOfferForm={setEditOfferForm}
        handleSaveOfferEdit={handleSaveOfferEdit}
        handleWithdrawOffer={handleWithdrawOffer}
        activeTheme={activeTheme}
        getMessagesForOffer={getMessagesForOffer}
        getUnreadMessagesForOffer={getUnreadMessagesForOffer}
        expandedMessagesOfferId={expandedMessagesOfferId}
        setExpandedMessagesOfferId={setExpandedMessagesOfferId}
        currentUserId={currentUserId}
        messageInputs={messageInputs}
        setMessageInputs={setMessageInputs}
        handleSendMessage={handleSendMessage}
        handleMarkMessagesAsRead={handleMarkMessagesAsRead}
      />
    </>
  )
}